### ISSUE TITLE
Pallet Contracts is outdated and cannot upload contract

### ISSUE THREAD

**Issue by charmitro** [CherryNetwork/Cherry-Node#30]
This is either an issue with a Polkadotjs Apps frontend or a compatibility issue with our version of `pallet_contracts` and [cargo-contract](https://github.com/paritytech/cargo-contract)

**Comment by charmitro** [comment]
I believe we should remove `pallet_contracts` from the runtime until we have the right compatibility ready.

cc. @zycon91 @therealcherry

**Comment by zycon91** [comment]
> I believe we should remove `pallet_contracts` from the runtime until we have the correct compatibility ready.
> 
> cc. @zycon91 @therealcherry

Sounds like a plan.

**Comment by charmitro** [comment]
> 

Assigned to you @zycon91
