### ISSUE TITLE
Add `created_at` & `to_delete_at` in IPFS storage asset

### ISSUE THREAD

**Issue by charmitro** [CherryNetwork/Cherry-Node#37]
Both have to be date. Look into substrate(maybe timestamp(?)) for counting time → blocks or vice versa or just time

**Comment by charmitro** [comment]
Whats your opinion about this @zycon91 ?

**Comment by zycon91** [comment]
I think we have to go with blocks -> time. Will look more into it!

**Comment by charmitro** [comment]
> I think we have to go with blocks → time. Will look more into it!

You can always do MINUTES/HOURS/DAYS just like we do for our runtime. https://github.com/CherryNetwork/Cherry-Node/blob/027ed9ff34d8fb32b718190b7b53e4b7bd3ba715/bin/node/runtime/src/constants.rs#L102-L104

Maybe even add a new constant for our needs.

**Comment by zycon91** [comment]
> > I think we have to go with blocks → time. Will look more into it!
> 
> You can always do MINUTES/HOURS/DAYS just like we do for our runtime.
> 
> https://github.com/CherryNetwork/Cherry-Node/blob/027ed9ff34d8fb32b718190b7b53e4b7bd3ba715/bin/node/runtime/src/constants.rs#L102-L104
> 
> Maybe even add a new constant for our needs.

Great idea! Added this constant and will start working on the issue!

https://github.com/CherryNetwork/Cherry-Node/blob/f8e2299b7499ce41ce7bcf64df4eefddd67d0530/bin/node/runtime/src/constants.rs#L39-L43

**Comment by zycon91** [comment]
> > I think we have to go with blocks → time. Will look more into it!
> 
> You can always do MINUTES/HOURS/DAYS just like we do for our runtime.
> 
> https://github.com/CherryNetwork/Cherry-Node/blob/027ed9ff34d8fb32b718190b7b53e4b7bd3ba715/bin/node/runtime/src/constants.rs#L102-L104
> 
> Maybe even add a new constant for our needs.

Great idea! Will add a constant and start working on the issue!

**Comment by zycon91** [comment]
Added a new constant like you suggested.

https://github.com/CherryNetwork/Cherry-Node/blob/2f10d158efd5510b860c3c42f520a62f87b9e19c/bin/node/runtime/src/constants.rs#L106

And I also added a new type to pallet_ipfs so that I can pass the constant.

https://github.com/CherryNetwork/Cherry-Node/blob/2f10d158efd5510b860c3c42f520a62f87b9e19c/bin/node/runtime/src/lib.rs#L1252-L1255
https://github.com/CherryNetwork/Cherry-Node/blob/2f10d158efd5510b860c3c42f520a62f87b9e19c/bin/node/runtime/src/lib.rs#L1263

At the moment I only count blocks (created_at and deleting_at). I think it can work nicely!

**Comment by charmitro** [comment]
> Added a new constant like you suggested.
> 
> https://github.com/CherryNetwork/Cherry-Node/blob/2f10d158efd5510b860c3c42f520a62f87b9e19c/bin/node/runtime/src/constants.rs#L106
> 
> And I also added a new type to pallet_ipfs so that I can pass the constant.
> 
> https://github.com/CherryNetwork/Cherry-Node/blob/2f10d158efd5510b860c3c42f520a62f87b9e19c/bin/node/runtime/src/lib.rs#L1252-L1255
> 
> 
> https://github.com/CherryNetwork/Cherry-Node/blob/2f10d158efd5510b860c3c42f520a62f87b9e19c/bin/node/runtime/src/lib.rs#L1263
> 
> At the moment I only count blocks (created_at and deleting_at). I think it can work nicely!

Make sure to include a unit test about this before we proceed.

**Comment by zycon91** [comment]
I am assigning myself to #46, as it has a higher priority and it is more critical for mainnet. Whoever wants to take this issue till I resolve the more urgent issue, feel free to do it.

**Comment by charmitro** [comment]
@zycon91 provides us with what is left so @elsuizo can take care of it.

**Comment by elsuizo** [comment]
yeah lets give a try!!!

**Comment by zycon91** [comment]
Last time I was working on the task, I added the ```created_at``` and ```delete_at``` fields in the storage asset (both counting blocks) and used a constant to do that (```DefaultAssetLifetime```). I ran some tests creating assets and the numbers were correct. I didn't finish the unit test and we haven't discussed if we want to convert the blocknumber to time or not.

**Comment by charmitro** [comment]
> Last time I was working on the task, I added the `created_at` and `delete_at` fields in the storage asset (both counting blocks) and used a constant to do that (`DefaultAssetLifetime`). I ran some tests creating assets and the numbers were correct. I didn't finish the unit test and we haven't discussed if we want to convert the blocknumber to time or not.

We should stick with `BlockNumber` wherever we can.

@elsuizo working branch is `ipfs-storage` for this. Try to create some tests for the `create_at` & `delete_at` feature.
