### ISSUE TITLE
Multisig Sudo or Sudo with different layers

### ISSUE THREAD

**Issue by charmitro** [CherryNetwork/Cherry-Node#53]
Multisig Sudo account.

**OR**

Sudo account with different layers.

- One layer can have access/permissions to GoV Token.
- One layer can have access/permissions to updates.
- One layer can have access/permissions to Sudo Calls.
- One layer can have access/permissions for pausing all transactions.

**Comment by Chubek** [comment]
Here's my idea.

We make an enum, let's call it PermissionLevel, that holds our 4 permission levels plus a padding type. We then make a struct like `MultiPermission(type, type, tpye, type, type)`. This is where that padding type comes into play. So a multi permission type caan take in between 1 and 5 permissions, rest being the pad type. Why 5 possible types though? Don't we only got 4 types? I just want the possible multipremission types to be equal to the number of permission level enum types. Pad included. So all the types would invariably include a pad. This COULD be useful later, for example in type adding maybe? I think having a default pad is intuitive.

After that we create values in the chain storage with AccoundID and our selected multipermission sets. When we wish to do an extrinsic, we will have a utility function called check_permission that checks and validates the types with that account id.

Thanks. This is a rather coarse idea, please be easy on me :D

**Comment by zycon91** [comment]
Idea for the multiple layer Sudo:

We can add the 4 options (Gover, Updater, Sudoer, Pauser... or whatever names we want) to the following enum:
https://github.com/CherryNetwork/Cherry-Node/blob/c8fd3adea4664866c94441785bee54eca3d12126/frame/system/src/lib.rs#L796-L807

And then add some checks in the ensure_signed function:
https://github.com/CherryNetwork/Cherry-Node/blob/c8fd3adea4664866c94441785bee54eca3d12126/frame/system/src/lib.rs#L995-L1027

**Comment by charmitro** [comment]
@zycon91 @Chubek 
How often do we need these layers? Do they need to be available globally or are they pallet specific?

**Comment by zycon91** [comment]
> @zycon91 @Chubek How often do we need these layers? Do they need to be available globally or are they pallet specific?

I think we need them globally, but I need to check it first. I will have a more complete answer soon.

**Comment by charmitro** [comment]
> Actually, I think we need them only locally. All checks and functions are inside pallet_system.

That is correct I believe.



> Here's my idea.
> 
> We make an enum, let's call it PermissionLevel, that holds our 4 permission levels plus a padding type. We then make a struct like `MultiPermission(type, type, tpye, type, type)`. This is where that padding type comes into play. So a multi permission type caan take in between 1 and 5 permissions, rest being the pad type. Why 5 possible types though? Don't we only got 4 types? I just want the possible multipremission types to be equal to the number of permission level enum types. Pad included. So all the types would invariably include a pad. This COULD be useful later, for example in type adding maybe? I think having a default pad is intuitive.
> 
> After that we create values in the chain storage with AccoundID and our selected multipermission sets. When we wish to do an extrinsic, we will have a utility function called check_permission that checks and validates the types with that account id.
> 
> The validator could be simple, with a signature like (&owner, extrinsic) it will just check if the extrinsic permission exists in that storage value.
> 
> Thanks. This is a rather coarse idea, please be easy on me :D

@Chubek Your idea would work for a general purpose runtime but not for our kind of runtime becaues of all the add-on modules.

@zycon91 @Chubek @elsuizo We should go ahead and research how we can add more `ensure-*` checks in the `frame_system` module.

**Comment by Chubek** [comment]
https://github.com/CherryNetwork/Cherry-Node/blob/b908e11a9bd3fcfc7b0820dc5e55351d4c16859c/frame/system/src/lib.rs

Let's take a look at ensure_signed for example

```
/// Ensure that the origin `o` represents a signed extrinsic (i.e. transaction).
/// Returns `Ok` with the account that signed the extrinsic or an `Err` otherwise.
pub fn ensure_signed<OuterOrigin, AccountId>(o: OuterOrigin) -> Result<AccountId, BadOrigin>
where
	OuterOrigin: Into<Result<RawOrigin<AccountId>, OuterOrigin>>,
{
	match o.into() {
		Ok(RawOrigin::Signed(t)) => Ok(t),
		_ => Err(BadOrigin),
	}
}
```


My first intuition is, we add our layers to RawOrigin enum. Who's with me? :D

**Comment by charmitro** [comment]
## Regarding `Updater`

**Technical Committee** is an `Instance` of `pallet_collective`: https://github.com/CherryNetwork/Cherry-Node/blob/fab7bb16a28401e2bd7a40db11ddf1407feb4c6c/bin/node/runtime/src/lib.rs#L647-L657

That means that changes made to `pallet_collective` will interfere with other instances such as the `Council`: https://github.com/CherryNetwork/Cherry-Node/blob/fab7bb16a28401e2bd7a40db11ddf1407feb4c6c/bin/node/runtime/src/lib.rs#L594-L604

We should proceed with creating a new Pallet called `pallet-updater` which will be a mix of `pallet_sudo` & `pallet_collective`(think of it like a sudo with multiple members).

@zycon91 @Chubek let's go with this approach for `Updater` and we'll take care of `Gover` after this is completed

**Comment by charmitro** [comment]
@Chubek @zycon91 Let's get this done by creating tests & benchmarks for the new pallet.
