### ISSUE TITLE
Creating a recurring proposal seem to be broken

### ISSUE THREAD

**Issue by charmitro** [CherryNetwork/Cherry-Node#83]
####  Steps to reproduce
Create a recurring proposal through the `proposeSpend` extrinsic

branch: `dev`

**Comment by charmitro** [comment]
@zycon91 You can also try to use the new implementation of the proposal modal from [Cherry Apps](https://github.com/CherryNetwork/apps) on branch [feature/treasury-recurring-proposals](https://github.com/CherryNetwork/apps/tree/feature/treasury-recurring-proposals)

**Comment by zycon91** [comment]
> @zycon91 You can also try to use the new implementation of the proposal modal from [Cherry Apps](https://github.com/CherryNetwork/apps) on branch [feature/treasury-recurring-proposals](https://github.com/CherryNetwork/apps/tree/feature/treasury-recurring-proposals)

I cannot click the `submit proposal` button. Also I think there is something wrong with the `segments` data type. Sending a screenshot. 

![Screenshot 2022-04-26 at 7 09 41 PM](https://user-images.githubusercontent.com/65149624/165345349-27106e6c-7667-48e9-b9be-2d02a330f295.png)

I could reproduce the bug from `dev`. Will work on it.

**Comment by charmitro** [comment]
> > @zycon91 You can also try to use the new implementation of the proposal modal from [Cherry Apps](https://github.com/CherryNetwork/apps) on branch [feature/treasury-recurring-proposals](https://github.com/CherryNetwork/apps/tree/feature/treasury-recurring-proposals)
> 
> I cannot click the `submit proposal` button. Also I think there is something wrong with the `segments` data type. Sending a screenshot.
> 
> ![Screenshot 2022-04-26 at 7 09 41 PM](https://user-images.githubusercontent.com/65149624/165345349-27106e6c-7667-48e9-b9be-2d02a330f295.png)
> 
> I could reproduce the bug from `dev`. Will work on it.

Try the new branch [treasury-recurring-proposals-fix](https://github.com/CherryNetwork/apps/tree/feature/treasury-recurring-proposals-fix)

**Comment by zycon91** [comment]
> > > @zycon91 You can also try to use the new implementation of the proposal modal from [Cherry Apps](https://github.com/CherryNetwork/apps) on branch [feature/treasury-recurring-proposals](https://github.com/CherryNetwork/apps/tree/feature/treasury-recurring-proposals)
> > 
> > 
> > I cannot click the `submit proposal` button. Also I think there is something wrong with the `segments` data type. Sending a screenshot.
> > ![Screenshot 2022-04-26 at 7 09 41 PM](https://user-images.githubusercontent.com/65149624/165345349-27106e6c-7667-48e9-b9be-2d02a330f295.png)
> > I could reproduce the bug from `dev`. Will work on it.
> 
> Try the new branch [treasury-recurring-proposals-fix](https://github.com/CherryNetwork/apps/tree/feature/treasury-recurring-proposals-fix)

Works as intended both on extrinsic and the modal of the new branch (`treasury-recurring-proposal-fix`). We have changed how the `waiting proposals` work in a previous PR, so everything works just fine.

**Comment by charmitro** [comment]
> > > > @zycon91 You can also try to use the new implementation of the proposal modal from [Cherry Apps](https://github.com/CherryNetwork/apps) on branch [feature/treasury-recurring-proposals](https://github.com/CherryNetwork/apps/tree/feature/treasury-recurring-proposals)
> > > 
> > > 
> > > I cannot click the `submit proposal` button. Also I think there is something wrong with the `segments` data type. Sending a screenshot.
> > > ![Screenshot 2022-04-26 at 7 09 41 PM](https://user-images.githubusercontent.com/65149624/165345349-27106e6c-7667-48e9-b9be-2d02a330f295.png)
> > > I could reproduce the bug from `dev`. Will work on it.
> > 
> > 
> > Try the new branch [treasury-recurring-proposals-fix](https://github.com/CherryNetwork/apps/tree/feature/treasury-recurring-proposals-fix)
> 
> Works as intended both on extrinsic and the modal of the new branch (`treasury-recurring-proposal-fix`). We have changed how the `waiting proposals` work in a previous PR, so everything works just fine.

Perfect, closing this issue.
