### ISSUE TITLE
Disapproved proposals should be moved to the `waiting_proposals` storage

### ISSUE THREAD

**Issue by zycon91** [CherryNetwork/Cherry-Node#90]
When a treasury proposal gets disapproved it stays in the `proposals` storage of `pallet_treasury`. We should make all the disapproved proposals go to the `waiting_proposals` storage.

**Comment by charmitro** [comment]
Does this make any sense? If something gets declined we should completely delete it. @zycon91  @therealcherry

**Comment by zycon91** [comment]
> Does this make any sense? If something gets declined we should completely delete it. @zycon91 @therealcherry

yea. I agree. We should probably delete it.
